name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            output_file: vimana-linux.zip
            make_command: build-linux
          # - os: arm-mac # , arm-mac, amd-mac
          #   output_file: vimana-macos-arm64.zip
          #   make_command: build
          # - os: amd-mac
          #   output_file: vimana-macos-amd64.zip
          #   make_command: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Run tests
        run: make test

      - name: Build Vimana
        run: make ${{ matrix.make_command }} && make build

      - name: Package Vimana for linux
        run: zip ${{ matrix.output_file }} vimana-linux

      - name: Package Vimana for mac
        run: zip vimana-mac vimana-mac

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.output_file }}
          path: ${{ matrix.output_file }}

      - name: Upload Artifacts Mac
        uses: actions/upload-artifact@v2
        with:
          name: vimana-mac.zip
          path: vimana-mac.zip

